In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data = pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# In this estimated salary is going to be the output feature and remaining will be the independent feature
# That's the reason why output feature is a continuous variable and it then turns out to be a regression problem
data = data.drop(['RowNumber', 'CustomerId','Surname'],axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [8]:
# Encode the Geography using One-Hot encoder
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [10]:
# Combining onehot encoded columns with the data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [ ]:
# Splitting the data into independent features and target feature
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [12]:
# Splitting the data in train-test set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [13]:
# Scaling down the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
with open('label_encoder_gender_reg.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo_reg.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler_reg.pkl','wb') as file:
    pickle.dump(scaler,file)

In [18]:
# Train ANN for Regression

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping, TensorBoard 
import datetime

In [16]:
# Building the model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), # Input -> Hidden layer 1
    Dense(32,activation='relu'), # Hidden layer 1 -> Hidden layer 2
    Dense(1) # Hidden layer 2 -> Output Default activation function applied here is Linear Activation function
])

d:\GenAICourse\ANN-BinaryClassification\annenv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [17]:
# Compiling the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [19]:
# Setting up TensorBoard
log_dir = 'regressionlogs/fit/' +datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorboard_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [20]:
# Setting up early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [21]:
history = model.fit(
    X_train, y_train,
    validation_data = (X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 6ms/step - loss: 100374.9297 - mae: 100374.9297 - val_loss: 98507.5781 - val_mae: 98507.5781
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 99599.2578 - mae: 99599.2578 - val_loss: 96943.4922 - val_mae: 96943.4922
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 96883.3125 - mae: 96883.3125 - val_loss: 92952.7188 - val_mae: 92952.7188
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 91549.1172 - mae: 91549.1172 - val_loss: 86332.4531 - val_mae: 86332.4531
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 83846.6641 - mae: 83846.6641 - val_loss: 77802.8906 - val_mae: 77802.8906
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 74767.6797 - mae: 74767.6797 - val_loss: 68910.7969 - val_mae: 68910.7969
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 65923.0781 - mae: 65923.0781 - val_loss: 61207.0781 - val_mae: 61207.0781
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 58875.4648 - mae: 58875.4648 - val_loss: 55715.0625 - val_mae: 55715.0625
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 54319.1562 - mae: 54319.1562 - val_loss: 52688.6094 - val_mae: 52688.6094
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 51853.8398 - mae: 51853.8398 - val_loss: 51337.1641 - val_mae: 51337.1641
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50798.2461 - mae: 50798.2461 - val_loss: 50925.4922 - val_mae: 50925.4922
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50400.1016 - mae: 50400.1016 - val_loss: 50780.1953 - val_mae: 50780.1953
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50233.5039 - mae: 50233.5039 - val_loss: 50699.0078 - val_mae: 50699.0078
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50145.9531 - mae: 50145.9531 - val_loss: 50646.2070 - val_mae: 50646.2070
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50073.4141 - mae: 50073.4141 - val_loss: 50603.8828 - val_mae: 50603.8828
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50021.3242 - mae: 50021.3242 - val_loss: 50564.8438 - val_mae: 50564.8438
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49976.3398 - mae: 49976.3398 - val_loss: 50548.2930 - val_mae: 50548.2930
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49941.8633 - mae: 49941.8633 - val_loss: 50519.2344 - val_mae: 50519.2344
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49905.8086 - mae: 49905.8086 - val_loss: 50490.7227 - val_mae: 50490.7227
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49871.3320 - mae: 49871.3320 - val_loss: 50470.0352 - val_mae: 50470.0352
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49843.1211 - mae: 49843.1211 - val_loss: 50452.2227 - val_mae: 50452.2227
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49812.5117 - mae: 49812.5117 - val_loss: 50423.1055 - val_mae: 50423.1055
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49791.6094 - mae: 49791.6094 - val_loss: 50412.1562 - val_mae: 50412.1562
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49767.7734 - mae: 49767.7734 - val_loss: 50390.4141 - val_mae: 50390.4141
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49748.6562 - mae: 49748.6562 - val_loss: 50376.2656 - val_mae: 50376.2656
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49722.2461 - mae: 49722.2461 - val_loss: 50370.0039 - val_mae: 50370.0039
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49708.0039 - mae: 49708.0039 - val_loss: 50351.0117 - val_mae: 50351.0117
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49688.2109 - mae: 49688.2109 - val_loss: 50347.1289 - val_mae: 50347.1289
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49667.8633 - mae: 49667.8633 - val_loss: 50336.1680 - val_mae: 50336.1680
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49654.0977 - mae: 49654.0977 - val_loss: 50333.6836 - val_mae: 50333.6836
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49638.8242 - mae: 49638.8242 - val_loss: 50326.6484 - val_mae: 50326.6484
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49627.1836 - mae: 49627.1836 - val_loss: 50323.9414 - val_mae: 50323.9414
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49619.1055 - mae: 49619.1055 - val_loss: 50315.3789 - val_mae: 50315.3789
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49604.7188 - mae: 49604.7188 - val_loss: 50310.7539 - val_mae: 50310.7539
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49587.9453 - mae: 49587.9453 - val_loss: 50307.1328 - val_mae: 50307.1328
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49580.6250 - mae: 49580.6250 - val_loss: 50309.2188 - val_mae: 50309.2188
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49570.8008 - mae: 49570.8008 - val_loss: 50315.3359 - val_mae: 50315.3359
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49561.3203 - mae: 49561.3203 - val_loss: 50311.1602 - val_mae: 50311.1602
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49554.3828 - mae: 49554.3828 - val_loss: 50304.9844 - val_mae: 50304.9844
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49546.6250 - mae: 49546.6250 - val_loss: 50295.6719 - val_mae: 50295.6719
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49533.7891 - mae: 49533.7891 - val_loss: 50285.9453 - val_mae: 50285.9453
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49526.1328 - mae: 49526.1328 - val_loss: 50290.0508 - val_mae: 50290.0508
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49517.6484 - mae: 49517.6484 - val_loss: 50288.1289 - val_mae: 50288.1289
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49511.5742 - mae: 49511.5742 - val_loss: 50279.9336 - val_mae: 50279.9336
Epoch 45/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49507.2891 - mae: 49507.2891 - val_loss: 50276.2930 - val_mae: 50276.2930
Epoch 46/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49495.6758 - mae: 49495.6758 - val_loss: 50275.5977 - val_mae: 50275.5977
Epoch 47/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49488.9258 - mae: 49488.9258 - val_loss: 50273.4062 - val_mae: 50273.4062
Epoch 48/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49483.8242 - mae: 49483.8242 - val_loss: 50276.1211 - val_mae: 50276.1211
Epoch 49/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49478.6406 - mae: 49478.6406 - val_loss: 50277.9844 - val_mae: 50277.9844
Epoch 50/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49471.2539 - mae: 49471.2539 - val_loss: 50278.3672 - val_mae: 50278.3672
Epoch 51/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49465.4414 - mae: 49465.4414 - val_loss: 50270.2969 - val_mae: 50270.2969
Epoch 52/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49459.5391 - mae: 49459.5391 - val_loss: 50277.3750 - val_mae: 50277.3750
Epoch 53/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49453.2383 - mae: 49453.2383 - val_loss: 50273.2539 - val_mae: 50273.2539
Epoch 54/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49448.0742 - mae: 49448.0742 - val_loss: 50279.1094 - val_mae: 50279.1094
Epoch 55/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49441.7969 - mae: 49441.7969 - val_loss: 50282.1289 - val_mae: 50282.1289
Epoch 56/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49435.1992 - mae: 49435.1992 - val_loss: 50274.1367 - val_mae: 50274.1367
Epoch 57/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 49430.6328 - mae: 49430.6328 - val_loss: 50282.6367 - val_mae: 50282.6367
Epoch 58/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49425.9609 - mae: 49425.9609 - val_loss: 50281.0000 - val_mae: 50281.0000
Epoch 59/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49418.3203 - mae: 49418.3203 - val_loss: 50283.9844 - val_mae: 50283.9844
Epoch 60/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49412.7969 - mae: 49412.7969 - val_loss: 50290.0312 - val_mae: 50290.0312
Epoch 61/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49406.3086 - mae: 49406.3086 - val_loss: 50298.0078 - val_mae: 50298.0078

In [22]:
%load_ext tensorboard

In [26]:
%tensorboard --logdir regressionlogs/fit

Reusing TensorBoard on port 6007 (pid 33024), started 0:00:12 ago. (Use '!kill 33024' to kill it.)

In [27]:
# Evaluate model on test data
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f"Test MAE : {test_mae:.2f}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 50270.2969 - mae: 50270.2969
Test MAE : 50270.30

In [29]:
model.save('regression_model.keras')