In [3]:
import warnings

# Suppress all UserWarning messages
warnings.filterwarnings("ignore", category=UserWarning)

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [4]:
data = pd.read_csv('../data/Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
# In this estimated salary is going to be the output feature and remaining will be the independent feature
# That's the reason why output feature is a continuous variable and it then turns out to be a regression problem
data = data.drop(['RowNumber', 'CustomerId','Surname'],axis=1)

In [6]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [7]:
# Encode the Geography using One-Hot encoder
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [8]:
# Combining onehot encoded columns with the data
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [9]:
# Splitting the data into independent features and target feature
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [10]:
# Splitting the data in train-test set
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2,random_state=42)

In [11]:
# Scaling down the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [12]:
with open('label_encoder_gender_reg.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)

with open('onehot_encoder_geo_reg.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)

with open('scaler_reg.pkl','wb') as file:
    pickle.dump(scaler,file)

In [13]:
# Train ANN for Regression

import tensorflow as tf
from keras.models import Sequential
from keras.layers import Dense
from keras.callbacks import EarlyStopping, TensorBoard 
import datetime

In [14]:
# Building the model
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)), # Input -> Hidden layer 1
    Dense(32,activation='relu'), # Hidden layer 1 -> Hidden layer 2
    Dense(1) # Hidden layer 2 -> Output Default activation function applied here is Linear Activation function
])

In [15]:
# Compiling the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])
model.summary()

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │           832 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,945 (11.50 KB)

 Trainable params: 2,945 (11.50 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
# Setting up TensorBoard
log_dir = 'regressionlogs/fit/' +datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorboard_callback = TensorBoard(log_dir=log_dir,histogram_freq=1)

In [17]:
# Setting up early stopping
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [18]:
history = model.fit(
    X_train, y_train,
    validation_data = (X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback,tensorboard_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 4s 9ms/step - loss: 100379.3125 - mae: 100379.3125 - val_loss: 98527.8750 - val_mae: 98527.8750
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 99669.5703 - mae: 99669.5703 - val_loss: 97084.8281 - val_mae: 97084.8281
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 97146.3594 - mae: 97146.3594 - val_loss: 93376.0859 - val_mae: 93376.0859
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 92149.1875 - mae: 92149.1875 - val_loss: 87115.7578 - val_mae: 87115.7578
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 84845.2891 - mae: 84845.2891 - val_loss: 78995.5312 - val_mae: 78995.5312
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 76145.2500 - mae: 76145.2500 - val_loss: 70421.1250 - val_mae: 70421.1250
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 67491.2578 - mae: 67491.2578 - val_loss: 62683.2734 - val_mae: 62683.2734
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 60321.3438 - mae: 60321.3438 - val_loss: 56951.4844 - val_mae: 56951.4844
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 55422.2383 - mae: 55422.2383 - val_loss: 53398.7852 - val_mae: 53398.7852
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 52616.6758 - mae: 52616.6758 - val_loss: 51603.8242 - val_mae: 51603.8242
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 51237.5391 - mae: 51237.5391 - val_loss: 50778.8750 - val_mae: 50778.8750
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 50575.3906 - mae: 50575.3906 - val_loss: 50490.7930 - val_mae: 50490.7930
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50272.1484 - mae: 50272.1484 - val_loss: 50368.5859 - val_mae: 50368.5859
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 50115.9570 - mae: 50115.9570 - val_loss: 50309.2305 - val_mae: 50309.2305
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 5ms/step - loss: 50031.5547 - mae: 50031.5547 - val_loss: 50269.6016 - val_mae: 50269.6016
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49969.3672 - mae: 49969.3672 - val_loss: 50242.2539 - val_mae: 50242.2539
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49926.4648 - mae: 49926.4648 - val_loss: 50223.1914 - val_mae: 50223.1914
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49898.5039 - mae: 49898.5039 - val_loss: 50204.4453 - val_mae: 50204.4453
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49867.1172 - mae: 49867.1172 - val_loss: 50188.0117 - val_mae: 50188.0117
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49836.9883 - mae: 49836.9883 - val_loss: 50190.6484 - val_mae: 50190.6484
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49815.2188 - mae: 49815.2188 - val_loss: 50173.7422 - val_mae: 50173.7422
Epoch 22/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49794.3008 - mae: 49794.3008 - val_loss: 50167.4727 - val_mae: 50167.4727
Epoch 23/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49771.8047 - mae: 49771.8047 - val_loss: 50166.0078 - val_mae: 50166.0078
Epoch 24/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49755.6953 - mae: 49755.6953 - val_loss: 50157.2188 - val_mae: 50157.2188
Epoch 25/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49740.3828 - mae: 49740.3828 - val_loss: 50151.8555 - val_mae: 50151.8555
Epoch 26/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49720.1758 - mae: 49720.1758 - val_loss: 50156.3906 - val_mae: 50156.3906
Epoch 27/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49703.5352 - mae: 49703.5352 - val_loss: 50151.7109 - val_mae: 50151.7109
Epoch 28/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49689.0469 - mae: 49689.0469 - val_loss: 50156.1719 - val_mae: 50156.1719
Epoch 29/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49676.2695 - mae: 49676.2695 - val_loss: 50154.2422 - val_mae: 50154.2422
Epoch 30/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49659.7461 - mae: 49659.7461 - val_loss: 50147.2031 - val_mae: 50147.2031
Epoch 31/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49652.1484 - mae: 49652.1484 - val_loss: 50142.7891 - val_mae: 50142.7891
Epoch 32/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49635.5547 - mae: 49635.5547 - val_loss: 50149.7773 - val_mae: 50149.7773
Epoch 33/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 49625.1914 - mae: 49625.1914 - val_loss: 50147.6562 - val_mae: 50147.6562
Epoch 34/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49611.9258 - mae: 49611.9258 - val_loss: 50142.5703 - val_mae: 50142.5703
Epoch 35/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49603.1133 - mae: 49603.1133 - val_loss: 50144.2617 - val_mae: 50144.2617
Epoch 36/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49594.7617 - mae: 49594.7617 - val_loss: 50152.2422 - val_mae: 50152.2422
Epoch 37/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49587.1367 - mae: 49587.1367 - val_loss: 50155.1562 - val_mae: 50155.1562
Epoch 38/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49571.0703 - mae: 49571.0703 - val_loss: 50160.6328 - val_mae: 50160.6328
Epoch 39/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49564.2539 - mae: 49564.2539 - val_loss: 50165.6367 - val_mae: 50165.6367
Epoch 40/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49552.2891 - mae: 49552.2891 - val_loss: 50173.6328 - val_mae: 50173.6328
Epoch 41/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49543.6211 - mae: 49543.6211 - val_loss: 50177.9062 - val_mae: 50177.9062
Epoch 42/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49536.3789 - mae: 49536.3789 - val_loss: 50171.7773 - val_mae: 50171.7773
Epoch 43/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49525.3828 - mae: 49525.3828 - val_loss: 50175.9570 - val_mae: 50175.9570
Epoch 44/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 49521.1953 - mae: 49521.1953 - val_loss: 50179.1250 - val_mae: 50179.1250

In [19]:
%load_ext tensorboard

In [20]:
%tensorboard --logdir regressionlogs/fit

In [21]:
# Evaluate model on test data
test_loss,test_mae = model.evaluate(X_test,y_test)
print(f"Test MAE : {test_mae:.2f}")

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 50142.5703 - mae: 50142.5703
Test MAE : 50142.57

In [22]:
model.save('regression_model.keras')